# Generated by Django 5.1.3 on 2024-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='news.ProductOrder', to='news.product'),
        ),
    ]
